---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
  namespace: webapps  # Ensure the ConfigMap is in the correct namespace
data:
  eureka_server_address: http://eureka-lb:80/eureka/  # Use the correct Eureka service name and port
---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: webapps  # Ensure the Service is in the correct namespace
  labels:
    app: eureka
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: eureka
  ports:
  - port: 8761
    name: eureka
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: webapps  # Ensure the StatefulSet is in the correct namespace
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: "eureka"  # Matches the headless service name
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: realestate1234/discovery:3
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_server_address
---

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  namespace: webapps  # Ensure the Service is in the correct namespace
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: NodePort  # Expose the service externally
  ports:
  - port: 80
    targetPort: 8761  # Forward traffic to the Eureka container port
