apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-app
  template:
    metadata:
      labels:
        app: gateway-service-app
    spec:
      containers:
        - name: gateway-service-app
          image: realestate1234/gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8222
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-svc
spec:
  selector:
    app: gateway-service-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8222
      protocol: TCP
