apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer-service-app
  namespace: webapps  # Ensure the deployment is in the correct namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer-service-app  # Ensure this matches the label in the template
  template:
    metadata:
      labels:
        app: offer-service-app  # Ensure this matches the selector
    spec:
      containers:
        - name: offer-service-app
          image: realestate1234/offre
          imagePullPolicy: Always
          ports:
            - containerPort: 8050  # Ensure the application is listening on this port
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: offer-service-svc
  namespace: webapps  # Ensure the service is in the correct namespace
spec:
  selector:
    app: offer-service-app  # Ensure this matches the label in the deployment
  type: ClusterIP  # Use LoadBalancer or NodePort if external access is needed
  ports:
    - port: 80
      targetPort: 8050  # Ensure this matches the containerPort in the deployment
      protocol: TCP
