apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  namespace: webapps  # Ensure the deployment is in the correct namespace
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-app
          image: realestate1234/user:5
          imagePullPolicy: Always
          ports:
            - containerPort: 8090  # Ensure the application is listening on this port
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
  namespace: webapps  # Ensure the service is in the correct namespace
spec:
  selector:
    app: user-service-app
  type: NodePort  # Use LoadBalancer or NodePort if external access is needed
  ports:
    - port: 80
      targetPort: 8090  # Ensure this matches the containerPort in the deployment
      protocol: TCP
