spring:
  config:
    import: optional:configserver:http://10.100.171.16:8888  # Config Server URL
  application:
    name: user-service  # Name of the User Service

security:
  jwt:
    token:
      secret-key: my-secret-key  # JWT secret key
