spring:
  profiles:
    active: native  # Use native profile for local configuration files
  application:
    name: config-server  # Name of the Config Server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations  # Location of configuration files
server:
  port: 8888  # Port for the Config Server

eureka:
  instance:
    prefer-ip-address: true  # Use IP address instead of hostname for registration
    hostname: config-service-svc  # Use the service name for Eureka registration
    ip-address: 10.100.171.16  # IP address of the Config Server service
  client:
    register-with-eureka: true  # Register with Eureka
    fetch-registry: true  # Fetch the registry from Eureka
    serviceUrl:
      defaultZone: http://10.100.157.161:8761/eureka/  # Eureka server URL
