eureka:
  instance:
    hostname: 10.100.157.161  # Replace with the actual IP or hostname of your Eureka server
  client:
    service-url:
      defaultZone: http://10.100.157.161:8761/eureka/ 

spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0
