server:
  port: 8222  # Port for the Gateway Service

spring:
  application:
    name: gateway-service  # Name of the Gateway Service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery via Eureka
      routes:
        - id: user-service
          uri: lb://user-service  # Use Eureka service name for user-service
          predicates:
            - Path=/api/v1/users/**  # Route requests starting with /api/v1/users

        - id: offre-service
          uri: lb://offre-service  # Use Eureka service name for offre-service
          predicates:
            - Path=/api/v1/offres/**  # Route requests starting with /api/v1/offres

        - id: payment-service
          uri: lb://payment-service  # Use Eureka service name for payment-service
          predicates:
            - Path=/api/v1/planSubscription/**  # Route requests starting with /api/v1/planSubscription
