server:
  port: 8070
spring:
  data:
    mongodb:
      username: timaslilaila
      password: 7RiZRnQZYmJOKt7u
      host: localhost
      port: 27018
      database: payment
      authentication-database: admin
  cloud:
    config:
      uri: http://localhost:8888
  discovery:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

#application:
#  config:
#    users-url: http://localhost:8222/api/v1/users
#    offres-url: http://localhost:8222/api/v1/offres
