server:
  port: 8090  # Port for the User Service

spring:
  application:
    name: user-service  # Name of the User Service
  data:
    mongodb:
      uri: mongodb+srv://timaslilaila:7RIZRnQZYmJ0Kt7u@cluster1.sn5ld.mongodb.net/user?retryWrites=true&w=majority&appName=Cluster1
   #   username: timaslilaila
    #  password: 7RiZRnQZYmJOKt7u
    #  host: mongodb  # Use the MongoDB service name in Kubernetes
    #  port: 27017  # Default MongoDB port
    #  database: user
    #  authentication-database: admin
    

application:
  config:
    offres-url: http://offre-service-svc:80/api/v1/offres  # Use the offre-service service name
    payments-url: http://payment-service-svc:80/api/v1/payments  # Use the payment-service service name
